### ISSUE TITLE
Unit test test_tapply_weather_host_spus_train_pred from ae/test_pyida.py failed

### ISSUE THREAD

**Issue by mplpl** [IBM/nzpyida#13]
```
FAILED test_pyida.py::test_tapply_weather_host_spus_train_pred - AssertionError: number of records are not matching
=================================================== 1 failed, 13 passed, 17 warnings in 1054.07s (0:17:34) ===================================================
```

```
>       assert result.shape[0] == 35551, "number of records are not matching"
E       AssertionError: number of records are not matching
E       assert 35549 == 35551
```

**Comment by mplpl** [comment]
I looked at this test. It is calling NZFunTApply on a table with 142193 rows and is doing decision tree based classification. Then it takes 25% of data and runs the prediction storing the result in the output. Number of rows in that result is then compared with expected (hardcoded) value 35551 - in my case it was 35549 and the test failed.

However, since the code is called on each data slice, and 25% of rows is selected with rounding up, the number of output rows depends on number of data slices. For instance with 1 data slice (that I used to run this test), it is 35549, for 4 it would be 35550, for 16 - 35552 and so on.

IMHO the test should assume a range of acceptable results, and not a single value.

@vinay-kasireddy what do you think?

**Comment by vinay-kasireddy** [comment]
@mplpl How did you calculate it for 4 and 16?

If you check NzFunTApply result (a) on this page https://developer.ibm.com/articles/analyzing-weather-data-with-python-in-database-analytics/  there is no clear pattern to the data slice counts.

**Comment by mplpl** [comment]
I made a mistake when calculating the value for 4 data slices example - it should be 35549 (but it is still different than the value in this test).

Here is how I compute that:

Because in this test NZFunTApply is called with parallel=True it will run on SPUs and the code passed in code_str is called for each data slice. That means that train_test_split() invocation in that code (made to get 25% of the input data to perform a test) takes a data from a single data slice into account and so it depends on the size of that data slice.

With one data slice, 25% of 142193 gives 35548.25 that is rounded up by scikit-learn to 35549.

With 4 data slices, one of possible table split into data slices is 35548, 35548, 35548 and 35549 rows. 25% of each (rounded up) is 8887, 8887, 8887 and 8888 that sums up to 35549. Other splits are also possible and depends on how the distribution key was selected.

With 8 data slices, possible split is 17774 * 7 and 17775 and 25% of each is 4444 that sums up to 35552.

All these values are different than 35551 expected in the test.

**Comment by vinay-kasireddy** [comment]
Fix is delivered and merged,closing it.
