### ISSUE TITLE
Keep track of mapping current names of columns to the original ones in table

### ISSUE THREAD

**Issue by mrozpawel** [IBM/nzpyida#85]
Currently when we change the name of the columns and the indexer is among the names that are changed, we still keep the old name of the indxer in variable which results in some errors in other commands

**Comment by mrozpawel** [comment]
Problem is more general.
Our issue is that when we pass new names of columns we do not keep any mapping of the new names to the original names that are in the table itself. It spreads to many other fields not only keeping track of an indexer, but also simply to filtering columns by new names like in the example below:

`>>> iris1.head()`
  | SEPAL_LENGTH | SEPAL_WIDTH | PETAL_LENGTH | PETAL_WIDTH | CLASS | ID1
-- | -- | -- | -- | -- | -- | --
4.3 | 3.0 | 1.1 | 0.1 | Iris-setosa | 13
4.4 | 2.9 | 1.4 | 0.2 | Iris-setosa | 8
4.4 | 3.0 | 1.3 | 0.2 | Iris-setosa | 38
4.4 | 3.2 | 1.3 | 0.2 | Iris-setosa | 42
4.5 | 2.3 | 1.3 | 0.3 | Iris-setosa | 41

`>>> iris1.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species', 'id1']`
`>>> iris1.head()`
[...]
KeyError: "None of [Index(['species'], dtype='object', name='COLNAME')] are in the [index]"

**Comment by mplpl** [comment]
Fixed in 1.2
